version: '3.8'

services:
  mcp-google-calendar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-google-calendar
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped